# Generated by Django 2.2.12 on 2020-07-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='blog_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
